apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  RDBMS_ROOT_PASSWORD: mysqlrootpass
  RDBMS_USERNAME: testuser
  RDBMS_PASSWORD: testpassword
  RDBMS_DATABASE_NAME: testdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        # 1. MySQL 官方镜像使用的环境变量
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: RDBMS_ROOT_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: RDBMS_USERNAME
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: RDBMS_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: RDBMS_DATABASE_NAME

        # 2. 供其他容器使用的变量（统一格式）
        - name: RDBMS_SERVER_URL
          value: mysql
        - name: RDBMS_SERVER_PORT
          value: "3306"
        - name: RDBMS_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: RDBMS_USERNAME
        - name: RDBMS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: RDBMS_PASSWORD
        - name: RDBMS_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: RDBMS_DATABASE_NAME

        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "1024Mi"

        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - mysqladmin ping -u root -p"$MYSQL_ROOT_PASSWORD"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - mysql -u root -p"$MYSQL_ROOT_PASSWORD" -e "SELECT 1"
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql
